services:
  - docker:dind

stages:
  - build
  - package

build:
 image: microsoft/dotnet:1.1.2-sdk
 stage: build
 script:
  - 'dotnet restore'
  - 'dotnet build -c Release'
  - 'dotnet publish -c Release'
  - mkdir dotnetapp
  - cp -f src/GliderGun.Api/bin/Release/netcoreapp1.1/publish dotnetapp
 only:
   - master
 artifacts:
  paths:
    - dotnetapp/

package:
  image : docker:latest
  dependencies:
   - build
  stage: package
  script:
   - ls
   - export IMAGE_TAG=$(echo -en $CI_COMMIT_REF_NAME | tr -c '[:alnum:]_.-' '-')
   - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
   - docker build --pull -t "$CI_REGISTRY_IMAGE:$IMAGE_TAG" -t dd/managecompute/glider-gun-api -t dd/managecompute/glider-gun-api:stable -f docker-images/glider-gun-api/Dockerfile .
   - docker push "$CI_REGISTRY_IMAGE:$IMAGE_TAG"

  only:
    - master