image : microsoft/dotnet:1.1.2-sdk

services:
  - docker:dind

stages:
  - build
  - package

job1:
 stage: build
 script:
  - 'dotnet restore'
  - 'dotnet build -c Release'
 only:
   - master

job2:
 stage: package
 script: 
  - 'dotnet package -c Release'
  - 'docker build -t dd/managecompute/glider-gun-api -t dd/managecompute/glider-gun-api:stable -f .\docker-images\glider-gun-api\Dockerfile .'
 only:
   - master