# Setup
title:        Glider Gun
tagline:      Templated deployments using Docker, Terraform, and Ansible
baseurl:      "/glider-gun"
# paginate:     1

# About/contact
author:
  name:       Dimension Data Research
  url:        https://dimensiondataresearch.github.com/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
